"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.SEARCH_TEMPLATE = "\n<div ng-controller=\"SearchCtrl as ctrl\" class=\"rv-table-search table-control\">\n    <md-input-container md-no-float class=\"rv-table-search table-control\">\n        <input\n            ng-model=\"ctrl.searchText\"\n            ng-keyup=\"ctrl.updatedSearchText()\"\n            placeholder=\"{{ 'plugins.enhancedTable.search.placeholder' | translate }}\"/>\n    </md-input-container>\n    <md-icon ng-if=\"ctrl.searchText.length > 2\" ng-click=\"ctrl.clearSearch()\" md-svg-src=\"navigation:close\"></md-icon>\n    <md-icon ng-if=\"ctrl.searchText.length <= 2\" md-svg-src=\"action:search\">\n        <md-tooltip>{{ 'plugins.enhancedTable.search.placeholder' | translate }}</md-tooltip>\n    </md-icon>\n    <span class=\"rv-button-divider\"></span>\n</div>\n";
exports.CLEAR_FILTERS_TEMPLATE = "\n<div class=\"table-control\">\n    <md-button\n        ng-controller=\"ClearFiltersCtrl as ctrl\"\n        aria-label=\"{{ 'plugins.enhancedTable.table.filter.clear' | translate }}\"\n        class=\"md-icon-button black\"\n        rv-help=\"table-clear-button\"\n        ng-click=\"ctrl.clearFilters()\"\n        ng-disabled=\"ctrl.noActiveFilters()\">\n        <md-tooltip>{{ 'plugins.enhancedTable.table.filter.clear' | translate }}</md-tooltip>\n        <md-icon md-svg-src=\"community:filter-remove\"></md-icon>\n    </md-button>\n</div>\n";
exports.APPLY_TO_MAP_TEMPLATE = "\n<div class=\"table-control\">\n    <md-button\n        ng-controller=\"ApplyToMapCtrl as ctrl\"\n        aria-label=\"{{ 'plugins.enhancedTable.table.filter.apply' | translate }}\"\n        class=\"md-icon-button black\"\n        ng-click=\"ctrl.applyToMap()\"\n        ng-disabled=\"!ctrl.filtersChanged()\">\n        <md-tooltip>{{ 'plugins.enhancedTable.table.filter.apply' | translate }}</md-tooltip>\n        <md-icon md-svg-src=\"action:map-refresh\"></md-icon>\n    </md-button>\n</div>\n";
exports.COLUMN_VISIBILITY_MENU_TEMPLATE = "\n<md-menu-bar class=\"table-control\" ng-controller=\"ColumnVisibilityMenuCtrl as ctrl\">\n    <md-menu md-position-mode=\"target-right target\">\n        <md-button\n            aria-label=\"Menu\"\n            class=\"md-icon-button black\"\n            ng-click=\"$mdOpenMenu($event)\">\n            <md-tooltip>{{ 'plugins.enhancedTable.table.hideColumns' | translate }}</md-tooltip>\n            <md-icon md-svg-src=\"community:format-list-checks\"></md-icon>\n        </md-button>\n        <md-menu-content class=\"rv-menu rv-dense\">\n            <md-menu-item ng-repeat=\"col in ctrl.columnVisibilities\">\n                <md-button ng-click=\"ctrl.toggleColumn(col)\" aria-label=\"{{ col.title }}\" md-prevent-menu-close=\"md-prevent-menu-close\">\n                    <span style='flex-basis: auto; overflow-wrap:normal;'>{{col.title}}</span>\n                    <md-icon md-svg-icon=\"action:done\" ng-if=\"col.visibility\"></md-icon>\n                </md-button>\n            </md-menu-item>\n        </md-menu-content>\n    </md-menu>\n</md-menu-bar>\n";
exports.MENU_TEMPLATE = "\n<md-menu-bar class=\"table-control\" ng-controller=\"MenuCtrl as ctrl\">\n    <md-menu md-position-mode=\"target-right target\">\n        <md-button\n            aria-label=\"Menu\"\n            class=\"md-icon-button black\"\n            ng-click=\"$mdOpenMenu($event)\">\n            <md-icon md-svg-src=\"navigation:more_vert\"></md-icon>\n            <md-tooltip>{{ 'plugins.enhancedTable.menu.options' | translate }}</md-tooltip>\n        </md-button>\n        <md-menu-content class=\"rv-menu rv-dense\">\n            <md-menu-item type=\"radio\" ng-model=\"ctrl.maximized\" value=\"false\" ng-click=\"ctrl.setSize(ctrl.maximized)\" ng-if=\"!sizeDisabled\" rv-right-icon=\"none\">\n                {{ 'plugins.enhancedTable.menu.split' | translate }}\n            </md-menu-item>\n            <md-menu-item type=\"radio\" ng-model=\"ctrl.maximized\" value=\"true\" ng-click=\"ctrl.setSize(ctrl.maximized)\"  ng-if=\"!sizeDisabled\" rv-right-icon=\"none\">\n                {{ 'plugins.enhancedTable.menu.max' | translate }}\n            </md-menu-item>\n            <md-menu-divider class=\"rv-lg\"></md-menu-divider>\n            <md-menu-item type=\"checkbox\" ng-model=\"ctrl.filterByExtent\" ng-click=\"ctrl.filterExtentToggled()\" rv-right-icon=\"community:filter\">\n                {{ 'plugins.enhancedTable.menu.filter.extent' | translate }}\n            </md-menu-item>\n            <md-menu-item type=\"checkbox\" ng-model=\"ctrl.showFilter\" ng-click=\"ctrl.toggleFilters()\" rv-right-icon=\"community:filter\">\n                {{ 'plugins.enhancedTable.menu.filter.show' | translate }}\n            </md-menu-item>\n            <md-menu-divider></md-menu-divider>\n            <md-menu-item ng-if='ctrl.printEnabled'>\n                <md-button ng-click=\"ctrl.print()\">\n                    <md-icon md-svg-icon=\"action:print\"></md-icon>\n                    {{ 'plugins.enhancedTable.menu.print' | translate }}\n                </md-button>\n            </md-menu-item>\n            <md-menu-item>\n                <md-button ng-click=\"ctrl.export()\">\n                    <md-icon md-svg-icon=\"editor:insert_drive_file\"></md-icon>\n                    {{ 'plugins.enhancedTable.menu.export' | translate }}\n                </md-button>\n            </md-menu-item>\n        </md-menu-content>\n    </md-menu>\n</md-menu-bar>";
exports.MOBILE_MENU_BTN_TEMPLATE = "\n<div class=\"mobile-table-control\">\n    <md-button\n        ng-controller=\"MobileMenuCtrl as ctrl\"\n        class=\"md-icon-button black\"\n        ng-click=\"ctrl.toggleMenu()\">\n        <md-icon md-svg-src=\"navigation:more_vert\"></md-icon>\n    </md-button>\n</div>";
exports.MOBILE_MENU_TEMPLATE = "\n<div class=\"mobile-table-control mobile-table-menu\">\n    <div ng-if=\"visible\" class=\"panel-controls\">\n        <span ng-if=\"searchEnabled\">" + exports.SEARCH_TEMPLATE + "</span>\n        " + exports.COLUMN_VISIBILITY_MENU_TEMPLATE + "\n        " + exports.CLEAR_FILTERS_TEMPLATE + "\n        " + exports.APPLY_TO_MAP_TEMPLATE + "\n        " + exports.MENU_TEMPLATE + "\n    </div>\n</div>";
exports.RECORD_COUNT_TEMPLATE = "\n<p class=\"rv-record-count\" title=\"{{ 'filter.default.label.info' | translate:{range: scrollRecords, total: totalRecords, max: totalRecords} }}\" >\n    <span class=\"filterRecords\" ng-if=\"filtered == false\">{{ 'filter.default.label.info' | translate:{range: scrollRecords, total: totalRecords, max: totalRecords} }}</span>\n    <span class=\"filterRecords\" ng-if=\"filtered == true\">{{ 'filter.default.label.filtered' | translate:{range: scrollRecords, total: shownRecords, max: totalRecords} }}</span>\n</p>";
exports.DETAILS_TEMPLATE = function (oid) {
    return "<button ng-controller='DetailsAndZoomCtrl as ctrl' ng-click='ctrl.openDetails(" + oid + ")' md-ink-ripple class='md-icon-button rv-icon-16 md-button ng-scope enhanced-table-details' aria-label=\"{{ 'plugins.enhancedTable.detailsAndZoom.details' | translate }}\">\n        <md-icon md-svg-src=\"action:description\" aria-hidden='false' class='ng-scope' role='img'>\n            <md-tooltip  md-direction=\"top\">{{ 'plugins.enhancedTable.detailsAndZoom.details' | translate }}</md-tooltip>\n        </md-icon>\n    </button>";
};
exports.ZOOM_TEMPLATE = function (oid) {
    return "<button ng-controller='DetailsAndZoomCtrl as ctrl' ng-click='ctrl.zoomToFeature(" + oid + ")'  md-ink-ripple class='md-icon-button rv-icon-16 md-button ng-scope enhanced-table-zoom' aria-label=\"{{ 'plugins.enhancedTable.detailsAndZoom.zoom' | translate }}\">\n        <md-icon md-svg-src=\"action:zoom_in\" aria-hidden='false'>\n            <md-tooltip  md-direction=\"top\">{{ 'plugins.enhancedTable.detailsAndZoom.zoom' | translate }}</md-tooltip>\n        </md-icon>\n    </button>";
};
exports.NUMBER_FILTER_TEMPLATE = function (value, isStatic) {
    var minVal = (value === undefined) ? '' : (value.split(',')[0] !== 'null') ? parseInt(value.split(',')[0]) : '';
    var maxVal = (value === undefined) ? '' : (value.split(',')[1] !== 'null') ? parseInt(value.split(',')[1]) : '';
    if (isStatic === false) {
        return "<input class=\"rv-min\" style=\"width:50%\" type=\"text\" placeholder=\"min\" value='" + minVal + "'/>\n         <input class=\"rv-max\" style=\"width:50%\" type=\"text\" placeholder=\"max\" value='" + maxVal + "'/>";
    }
    return "<input class=\"rv-min\" style=\"width:45%; opacity: 0.4\" type=\"text\" placeholder=\"min\" value='" + minVal + "' disabled/>\n         <input class=\"rv-max\" style=\"width:45%; opacity: 0.4\" type=\"text\" placeholder=\"max\" value='" + maxVal + "' disabled/>";
};
exports.DATE_FILTER_TEMPLATE = function (value, isStatic) {
    if (isStatic === true) {
        return "<span>\n                 <md-datepicker md-placeholder=\"{{ 'plugins.enhancedTable.columnFilters.date.min' | translate }}\" ng-model='min' ng-change=\"minChanged()\" ng-disabled='true' style='opacity: 0.4'></md-datepicker>\n                 <md-datepicker md-placeholder=\"{{ 'plugins.enhancedTable.columnFilters.date.max' | translate }}\" ng-model='max' ng-change=\"maxChanged()\" ng-disabled='true' style='opacity: 0.4'></md-datepicker>\n             </span>";
    }
    return "<span>\n                 <md-datepicker md-placeholder=\"{{ 'plugins.enhancedTable.columnFilters.date.min' | translate }}\" ng-model='min' ng-change=\"minChanged()\"></md-datepicker>\n                 <md-datepicker md-placeholder=\"{{ 'plugins.enhancedTable.columnFilters.date.max' | translate }}\" ng-model='max' ng-change=\"maxChanged()\"></md-datepicker>\n             </span>";
};
exports.TEXT_FILTER_TEMPLATE = function (value, isStatic) {
    value = (value === undefined) ? '' : value;
    if (isStatic) {
        return "<input class='rv-input' type=\"text\" placeholder=\"{{ 'plugins.enhancedTable.columnFilters.text' | translate }}\"' disabled style='opacity: 0.4' value='" + value + "'/>";
    }
    return "<input class='rv-input' ng-model='input' ng-change='inputChanged()' type=\"text\" placeholder=\"{{ 'plugins.enhancedTable.columnFilters.text' | translate }}\"' value='" + value + "'/>";
};
exports.CUSTOM_HEADER_TEMPLATE = function (displayName) { return "\n<div class=\"column-header\">\n    <md-button class=\"custom-header-label\">" + displayName + "</md-button>\n    <md-icon ng-if=\"sortAsc\" class=\"rv-sort-arrow\" md-svg-icon=\"navigation:arrow_upward\"></md-icon>\n    <md-icon ng-if=\"sortDesc\" class=\"rv-sort-arrow\" md-svg-icon=\"navigation:arrow_downward\"></md-icon>\n    <div class=\"arrows\"></div>\n    <div class=\"reorder-icons\">\n        <md-button class=\"reorder-button md-icon-button move-left\" ng-disabled=\"min\">\n            <md-icon ng-style=\"{ 'font-size': '16px', height: '16px' }\" md-svg-icon=\"hardware:keyboard_arrow_left\"></md-icon>\n        </md-button>\n        <md-button class=\"reorder-button md-icon-button move-right\" ng-disabled=\"max\">\n            <md-icon ng-style=\"{ 'font-size': '16px', height: '16px' }\" md-svg-icon=\"hardware:keyboard_arrow_right\"></md-icon>\n        </md-button>\n    </div>\n</div>\n"; };
exports.SELECTOR_FILTER_TEMPLATE = function (value, isStatic) {
    if (isStatic === true) {
        return "<md-select placeholder=\"{{ 'plugins.enhancedTable.columnFilters.selector' | translate }}\" multiple=\"{{true}}\" md-on-close='selectionChanged() style='height: 20px; opacity: 0.4; color: lightgrey' ng-model=\"selectedOptions\" ng-disabled='true'>\n                         <md-option ng-value=\"option\" ng-repeat=\"option in options\">{{ option }}</md-option>\n                     </md-select>";
    }
    else {
        return "<md-select placeholder=\"{{ 'plugins.enhancedTable.columnFilters.selector' | translate }}\" multiple=\"{{true}}\" style='height: 20px' md-on-close='selectionChanged()' ng-model=\"selectedOptions\">\n                         <md-option ng-value=\"option\" ng-repeat=\"option in options\">{{ option }}</md-option>\n                     </md-select>";
    }
};
exports.PRINT_TABLE = function (title, cols, rws) {
    // make headers with the column names of the currently displayed columns
    var headers = "";
    var columnNames = Object.keys(cols).map(function (column) { return cols[column]; });
    columnNames.forEach(function (columnName) {
        if (columnName !== 'SHAPE' && columnName !== ' ' && columnName !== '') {
            headers += "<th style='width:200%; padding: 5px; border-bottom: 2px solid #000000'><div class='cell'>" + columnName + "</div></th>";
        }
    });
    var columns = "<thead><tr>" + headers + "</tr></thead>";
    // make rows
    // make sure row attributes are only pushed for columns that are currently displayed.
    var rows = "<tbody>" + rws.map(function (rowAttributes) {
        var eachRow = Object.keys(cols).map(function (attribute) { return rowAttributes.data[attribute]; });
        return "<tr>" + eachRow.map(function (r) {
            return "<td><div class='cell'>" + r + "</div></td>";
        }).join('') + "</tr>";
    }).join('') + "</tbody>";
    // return formatted HTML table
    return "<head>\n                <style>\n                    table {\n                        font-family: arial, sans-serif;\n                        border-collapse: collapse;\n                    }\n                    td, th {\n                        border-bottom: 1px solid #dddddd;\n                        text-align: left;\n                        padding: 3px;\n                        padding-right: 50px;\n                        min-width: 150px;\n                    }\n                    h1{\n                        font-family: arial, sans-serif;\n                    }\n                    .cell{\n                        min-height: 40px;\n                    }\n                </style>\n            </head>\n            <body class ='dt-print-view'>\n                <div>\n                    <h1 class=\"md-title\" style='padding:8px;'>Features: " + title + "</h1>\n                    <table>" + columns + rows + "</table>\n                </div>\n            </body>";
};
exports.TABLE_UPDATE_TEMPLATE = "<md-toast class=\"table-toast\">\n        <span class=\"md-toast-text flex\">{{ 'filter.default.label.outOfDate' | translate }}</span>\n        <md-button class=\"md-highlight\" ng-click=\"reloadTable()\">{{ 'filter.default.action.outOfDate' | translate }}</md-button>\n        <md-button ng-click=\"closeToast()\">{{ 'filter.default.action.hide' | translate }}</md-button>\n    </md-toast>";
exports.TABLE_LOADING_TEMPLATE = function (legendEntry) {
    // hhite match parent
    return "<div class=\"rv-table-splash\" style=\"position:inherit\">\n        <div class=\"rv-splash-count\">\n            <span class=\"rv-splash-count-current\">" + Math.floor(legendEntry.loadedFeatureCount) + "</span>\n                <svg class=\"rv-splash-count-slash\" height=\"50\" width=\"25\">\n                    <line x1=\"0\" y1=\"50\" x2=\"25\" y2=\"0\"></line>\n                </svg>\n            <span class=\"rv-splash-count-total\">" + legendEntry.featureCount + "</span>\n        </div>\n        <span class=\"rv-splash-message md-caption\">{{ " + Math.floor(legendEntry.loadedFeatureCount) + " < " + legendEntry.featureCount + " ? 'table.splash.loadingdata' : 'table.splash.buildingtable' | translate }} </span>\n        <md-progress-linear class=\"rv-progress-top\" md-mode=\"indeterminate\" ng-show=\"true\"></md-progress-linear>\n    </div>";
};
